In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize

nltk.download('punkt')

# Download the required Punkt Tokenizer Models if not already present
nltk.download('punkt_tab')

text = "Tokenization is the first step in text processing. It divides text into words or sentences."

#Word Tokenization
word_tokens = word_tokenize(text)
print("Word Tokens:", word_tokens)

# Sentence Tokenization
sentence_tokens = sent_tokenize(text)
print("Sentence Tokens:", sentence_tokens)

Word Tokens: ['Tokenization', 'is', 'the', 'first', 'step', 'in', 'text', 'processing', '.', 'It', 'divides', 'text', 'into', 'words', 'or', 'sentences', '.']
Sentence Tokens: ['Tokenization is the first step in text processing.', 'It divides text into words or sentences.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()
words = ['running', 'runs', 'ran','runner']
stemmed_words = [stemmer.stem(word) for word in words]
print("Stemmed Words:", stemmed_words)

Stemmed Words: ['run', 'run', 'ran', 'runner']


In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

words = ['running', 'better', 'ran','files']

lemmatized_words = [lemmatizer.lemmatize(word, pos='v') for word in words]
print("Lemmatized words:" ,lemmatized_words)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Lemmatized words: ['run', 'better', 'run', 'file']


In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
print(nltk.data.path)

['/root/nltk_data', '/usr/nltk_data', '/usr/share/nltk_data', '/usr/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']


In [ ]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root

True

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag_sents

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
sentence = "John is running quickly"
tokens = word_tokenize(sentence)
pos_tags = pos_tag_sents([tokens])

print("POS Tags:", pos_tags)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


POS Tags: [[('John', 'NNP'), ('is', 'VBZ'), ('running', 'VBG'), ('quickly', 'RB')]]


In [ ]:
!pip install transformers

In [ ]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

text = "Transformers are powerful models for NLP."
imputs = tokenizer(text, return_tensors="pt")
outputs = model(**imputs)
print(outputs.last_hidden_state.shape)



tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

torch.Size([1, 10, 768])


In [ ]:
import nltk
from nltk.corpus import stopwords
import string

nltk.download('stopwords')

text = "NLP is a fascinating field. It helps computers understand human language!"
text = text.lower()

text = text.translate(str.maketrans('', '', string.punctuation))

stop_words = set(stopwords.words('english'))
filtered_words = [word for word in text.split() if word not in stop_words]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

prompt = "Artificial Intelligence is the driving force behind"
inputs = tokenizer.encode(prompt, return_tensors = "pt")

outputs = model.generate(inputs, max_length = 100, num_return_sequences = 1, do_sample=True)
generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

print("Generated Text:",generated_text)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Generated Text: Artificial Intelligence is the driving force behind Google's growing use of artificial intelligence. But a similar process happens in other fields. Computer designers tend to focus on the fundamental questions of which algorithms are best at doing what, while at the same time using different algorithms at different locations.

This means, though, that AI might be a good fit for a wider spectrum of use cases, especially as a tool in the hands of developers. Even though many of these problems aren't the same as problems faced


In [ ]:
from transformers import pipeline

generator = pipeline("text-generation" ,model="gpt2")

prompt = "The future of technology lies in"
generated_text = generator(prompt, max_length=100, num_return_sequences=1)

print("Generated Text:",generated_text[0]['generated_text'])

Device set to use cpu
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


Generated Text: The future of technology lies in all things technology that is the potential of human beings; in an era where our very souls are in demand; where our actions directly effect more than just money…

In other words, if the future of human civilization is any indication, you can never be sure what you're going to find next.

—John Avlon

[Via The Verge]


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

sentence = "The students are learning advanced Python programming concepts"

tokens = word_tokenize(sentence)
print("Tokens:" ,tokens)

tags = pos_tag(tokens)
print("POS Tags:", tags)

lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(token, pos='v') for token in tokens]
print("Lemmatized Tokens:", lemmatized_tokens)

Tokens: ['The', 'students', 'are', 'learning', 'advanced', 'Python', 'programming', 'concepts']
POS Tags: [('The', 'DT'), ('students', 'NNS'), ('are', 'VBP'), ('learning', 'VBG'), ('advanced', 'JJ'), ('Python', 'NNP'), ('programming', 'NN'), ('concepts', 'NNS')]
Lemmatized Tokens: ['The', 'students', 'be', 'learn', 'advance', 'Python', 'program', 'concepts']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer

# Download the necessary NLTK resources.
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
# Make sure to download 'punkt_tab' for sentence tokenization
nltk.download('punkt_tab')

sentence = "The students are learning advanced Python programming concepts"

tokens = word_tokenize(sentence)
print("Tokens:" ,tokens)

tags = pos_tag(tokens)
print("POS Tags:", tags)

lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(token, pos='v') for token in tokens]
print("Lemmatized Tokens:", lemmatized_tokens)

Tokens: ['The', 'students', 'are', 'learning', 'advanced', 'Python', 'programming', 'concepts']
POS Tags: [('The', 'DT'), ('students', 'NNS'), ('are', 'VBP'), ('learning', 'VBG'), ('advanced', 'JJ'), ('Python', 'NNP'), ('programming', 'NN'), ('concepts', 'NNS')]
Lemmatized Tokens: ['The', 'students', 'be', 'learn', 'advance', 'Python', 'program', 'concepts']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ["NLP is fun and exciting.",
          "Deep Learning and NLP are related fields.",
          "Machine learning is the foundation of NLP."
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Document-Term Matrix:")
print(X.toarray())

Vocabulary: ['and' 'are' 'deep' 'exciting' 'fields' 'foundation' 'fun' 'is' 'learning'
 'machine' 'nlp' 'of' 'related' 'the']
Document-Term Matrix:
[[1 0 0 1 0 0 1 1 0 0 1 0 0 0]
 [1 1 1 0 1 0 0 0 1 0 1 0 1 0]
 [0 0 0 0 0 1 0 1 1 1 1 1 0 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = ["NLP is fun and exciting.",
          "Deep Learning and NLP are related fields.",
          "Machine learning is the foundation of NLP."
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("TF-IDF Representation :\n")
print(X.toarray())

Vocabulary: ['and' 'are' 'deep' 'exciting' 'fields' 'foundation' 'fun' 'is' 'learning'
 'machine' 'nlp' 'of' 'related' 'the']
TF-IDF Representation :

[[0.40619178 0.         0.         0.53409337 0.         0.
  0.53409337 0.40619178 0.         0.         0.31544415 0.
  0.         0.        ]
 [0.32412354 0.4261835  0.4261835  0.         0.4261835  0.
  0.         0.         0.32412354 0.         0.25171084 0.
  0.4261835  0.        ]
 [0.         0.         0.         0.         0.         0.4261835
  0.         0.32412354 0.32412354 0.4261835  0.25171084 0.4261835
  0.         0.4261835 ]]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Sample dataset
texts = [
    "I love this product!",
    "This is the worst experience ever.",
    "Amazing service and quality.",
    "I hate this place.",
    "Absolutely fantastic and wonderful!"
]
labels = [1, 0, 1, 0, 1]

# Vectorize text
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

# Train Naive Bayes model
model = MultinomialNB()
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")
text = "Barack Obama was the 44th President of the United States and he lives in Washington, D.C."

doc = nlp(text)

for ent in doc.ents:
    print(f"Entity: {ent.text}, Label: {ent.label_})")

Entity: Barack Obama, Label: PERSON)
Entity: 44th, Label: ORDINAL)
Entity: the United States, Label: GPE)
Entity: Washington, Label: GPE)
Entity: D.C., Label: GPE)


In [ ]:
from textblob import TextBlob

text = "The product is absolutely amazing and I love it!"
blob = TextBlob(text)

sentiment = blob.sentiment.polarity

print("Sentiment Polarity:", sentiment)

Sentiment Polarity: 0.6125


In [ ]:
from transformers import pipeline

translator = pipeline("translation", "Helsinki-NLP/opus-mt-en-hi")
text = "nigga"

translated = translator(text, max_length = 40)[0]
print("Translated Text:" ,translated['translation_text'])

Device set to use cpu


Translated Text: niga. kgm


In [ ]:
# summarization of text
from transformers import pipeline

summarizer = pipeline("summarization")
text ="""
    Natural language processing (NLP) is a subfield of artificial intelligence that focuses on the interaction between computers and human language.
    It involves the development of algorithms and models that enable computers to understand, interpret, and generate human language.",
"""
summary = summarizer(text, max_length=10, min_length=5, do_sample=False)
print("Summary: ", summary[0]['summary_text'])

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


Summary:   Natural language processing (NLP)
